//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee_Details.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee_details
    {
        public int pkid { get; set; }
        public string name { get; set; }
        public decimal salary { get; set; }
        public Nullable<decimal> yearofexp { get; set; }
        public string designation { get; set; }
        public Nullable<System.DateTime> joineddate { get; set; }
    }
}
